name: CI/CD Pipeline

on:
  pull_request:
    types: [merged]
    branches:
      - main
      - master
  release:
    types: [prereleased, released]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit SHA, Branch or Tag to deploy'
        required: false
        default: ''
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - sandbox
          - staging
          - production
      namespace:
        description: 'Kubernetes namespace (defaults to environment name)'
        required: false
      release_type:
        description: 'Type of release (auto, major, minor, patch)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
  push:
    branches: [main, master]

jobs:
  determine-environment:
    runs-on:
      group: sandbox
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      ref: ${{ steps.set-ref.outputs.ref }}
      prerelease: ${{ steps.set-env.outputs.prerelease }}
    steps:
      - name: Set environment based on event
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
            
            # Set prerelease flag based on environment
            if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
              echo "prerelease=false" >> $GITHUB_OUTPUT
            else
              echo "prerelease=true" >> $GITHUB_OUTPUT
            fi
            
          elif [[ "${{ github.event_name }}" == "release" && "${{ github.event.action }}" == "released" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "prerelease=false" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "release" && "${{ github.event.action }}" == "prereleased" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "prerelease=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "environment=sandbox" >> $GITHUB_OUTPUT
            echo "prerelease=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=sandbox" >> $GITHUB_OUTPUT
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "environment=skip" >> $GITHUB_OUTPUT
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Set reference (SHA, branch, tag)
        id: set-ref
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.ref }}" != "" ]]; then
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

  # Create or update semantic version for all deployments
  create-version:
    needs: determine-environment
    if: needs.determine-environment.outputs.environment != 'skip'
    uses: forus-coop/.github/.github/workflows/semver-release.yml@main
    with:
      release_type: ${{ github.event.inputs.release_type || 'auto' }}
      prerelease: ${{ needs.determine-environment.outputs.prerelease }}
      release_branch: ${{ github.ref_name }}
      runner_group: ${{ needs.determine-environment.outputs.environment }}
    secrets: inherit

  build:
    needs: [determine-environment, create-version]
    if: needs.determine-environment.outputs.environment != 'skip'
    uses: forus-coop/.github/.github/workflows/docker-build-push.yml@main
    with:
      # Use the semantic version tag for consistent versioning
      image_tag: ${{ needs.create-version.outputs.version_tag }}
      runner_group: ${{ needs.determine-environment.outputs.environment }}
    secrets: inherit

  deploy:
    needs: [determine-environment, build, create-version]
    if: needs.determine-environment.outputs.environment != 'skip'
    uses: forus-coop/.github/.github/workflows/helm-deploy.yml@main
    with:
      environment: ${{ needs.determine-environment.outputs.environment }}
      namespace: ${{ github.event.inputs.namespace || needs.determine-environment.outputs.environment }}
      # Use the semantic version tag for consistent versioning
      image_tag: ${{ needs.create-version.outputs.version_tag }}
      helm_values_file: './helm/${{ needs.determine-environment.outputs.environment }}.yaml'
    secrets: inherit 