name: Run Rails Migrations

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment to run migrations in"
      image_name:
        required: true
        type: string
        description: "Docker image name with tag to use for running migrations"
      repository_name:
        required: false
        type: string
        description: "Repository name for secrets path (defaults to github.event.repository.name)"
      aws_region:
        description: "AWS region"
        required: false
        type: string
        default: "us-west-2"

jobs:
  run-migrations:
    runs-on:
      group: ${{ inputs.environment }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set repository name
        id: set-repo-name
        run: |
          REPO_NAME="${{ inputs.repository_name }}"
          if [[ -z "$REPO_NAME" ]]; then
            REPO_NAME="${{ github.event.repository.name }}"
          fi
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Set secret name
        id: set-secret-name
        run: |
          SECRET_NAME="${{ inputs.environment }}/${{ steps.set-repo-name.outputs.repo_name }}/environment"
          echo "secret_name=$SECRET_NAME" >> $GITHUB_OUTPUT
          echo "Using AWS Secrets Manager path: $SECRET_NAME"

      - name: Get AWS Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,${{ steps.set-secret-name.outputs.secret_name }}
          parse-json-secrets: true

      - name: Run migrations with Docker
        run: |
          # Pull the existing image that was built in the build job
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_name }}

          # Set RAILS_ENV
          export RAILS_ENV=${{ inputs.environment }}

          # Run migrations with Docker
          docker run --rm \
            -e RAILS_ENV \
            --env-file <(env) \
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_name }} \
            bundle exec rake db:migrate --trace
